server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-db
    username: root
    password:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
